### ISSUE TITLE
Organizations endpoints

### ISSUE THREAD

**Issue by p-mongo** [mongodb/go-client-mongodb-atlas#100]
I attempted to implement organization retrieval for mongocli (https://github.com/mongodb/mongocli/issues/208, https://github.com/mongodb/mongocli/issues/207) but it seems mongodbatlas does not have anything to do with organizations. If this is accurate can the respective endpoints be added please?

**Comment by gssbzn** [comment]
Hi @p-mongo the reason we have kept Organizations out of this client is that some endpoints require you to have personal API keys which you can't get on Atlas anymore.
I can bring what we've done for the Ops Manager client but I'll let @themantissa decide on this first

**Comment by p-mongo** [comment]
I'm afraid I do not understand. There are [organization endpoints](https://docs.atlas.mongodb.com/reference/api/organizations/) documented in the api. I implemented a client for these endpoints [in Ruby](https://github.com/p-mongo/mongo-cloud/commit/c40edd66bba2eb4771cbd7dfe68aea602b066440). If there are some endpoints that require specific keys, and there is no way to provide those keys to mongodbatlas presently, I can see how implementing these endpoints may not make sense. But I do not understand why mongodbatlas would not expose operations which are usable using the normal credentials today.

**Comment by themantissa** [comment]
Thank you @gssbzn for the tag. Hi, @p-mongo currently there is no API method for creating organizations via the API for Atlas (see https://docs.atlas.mongodb.com/reference/api/organizations/) for the aforementioned reason, hence we have not included organizations in this client because it was, until recently, primarily used by infrastructure as code tools that do not well manage API resources that do not have all CRUD capabilities, i.e. organizations have read/update/delete but not create.  Currently organizations must be created within the Atlas UI.  

However, with this client increasingly being used by other tools we could consider adding organization support for the RUD.  In fact we have a PR we did not review and merge for this https://github.com/mongodb/go-client-mongodb-atlas/pull/33.   Depending on demand for this we can review potentially adding support for RUD.
