### ISSUE TITLE
Wrong type for cluster diskSizeGB

### ISSUE THREAD

**Issue by Knappek** [mongodb/go-client-mongodb-atlas#140]
The [API reference for creating a cluster](https://docs.atlas.mongodb.com/reference/api/clusters-create-one/) states that `diskSizeGB` must be a positive integer. This library [declares it to be a *float64](https://github.com/mongodb/go-client-mongodb-atlas/blob/master/mongodbatlas/clusters.go#L96). Isn't this a mistake?

**Comment by themantissa** [comment]
@leofigy or @coderGo93 this was originally created by DoU so want to get your opinions on this.  Thanks!

**Comment by themantissa** [comment]
@Knappek just fyi I've asked our team to respond and they have it on their list to do so.  Thanks!

**Comment by Knappek** [comment]
Thanks @themantissa. It's not urgent, I just realized it and wanted to know about it.

**Comment by leofigy** [comment]
Hi @Knappek, right it mentions it must be a positive integer, I think it was set to be a *float64 as a convention to represent a "number" in the json payload that is by default a float64, but other number attributes are now set as int64. So it's inconsistent now. @coderGo93 do you know if other calculations are done for the diskSizeGB? otherwise we could fix the type to be consistent with the rest of integer attributes.

**Comment by themantissa** [comment]
@coderGo93 any thoughts on this?   @Knappek does that help w/ the question?  We could slate this for improvement but it would cause some downstream impacts that may delay it till we could do all across the board.

**Comment by coderGo93** [comment]
Hi @Knappek , thanks for pointing out,it seems it's a wrong type, it needs to be changed to Integer according to the docs, @themantissa

**Comment by themantissa** [comment]
Created an internal ticket to get correct when works for impacted teams, ref: INTMDB-125.

**Comment by gssbzn** [comment]
We'll be closing this, free clusters (M0) have a non-configurable size of 0.5GB, even if you can't submit this value tot he API GETing or listing cluster for a project with an M0 will need this field to be a float
